# Generated by Django 4.2 on 2023-04-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_articulo_delete_curso_delete_entregable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='cantidad_requerida',
            field=models.IntegerField(null=True),
        ),
    ]
