# Generated by Django 4.2 on 2023-04-30 19:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_articulo_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='version',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
